name: Publish

on:
  push:
    tags:
      - '@bisquit/*'

jobs:
  publish:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      id-token: write
    steps:
      - uses: actions/checkout@v3
      - uses: pnpm/action-setup@v2
        with:
          version: 8
      - uses: actions/setup-node@v3
        with:
          node-version-file: '.nvmrc'
          cache: 'pnpm'
          registry-url: 'https://registry.npmjs.org'

      - name: install
        run: pnpm i

      - name: get tagged package
        id: tagged_package
        run: |
          PACKAGE_NAME=$(echo ${{ github.ref_name }})
          echo ::set-output name=name::$PACKAGE_NAME

      - name: publish npm packages
        # run: pnpm publish -r --access public --no-git-checks
        run: pnpm --filter "${{ steps.tagged_package.outputs.name }}" lint
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NODE_AUTH_TOKEN }}
          NPM_CONFIG_PROVENANCE: true
