name: Publish

on:
  push:
    tags:
      - '@bisquit/*'

jobs:
  tagged-package:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: pnpm/action-setup@v2
        with:
          version: 8
      - uses: actions/setup-node@v3
        with:
          node-version-file: '.nvmrc'

      - name: get tagged package
        id: tagged_package
        run: |
          PACKAGE_NAME=$(echo ${{ github.ref_name }} | sed -E "s/(@bisquit\/.+)@.+/\1/")
          echo $PACKAGE_NAME
          echo "name=$PACKAGE_NAME" >> $GITHUB_OUTPUT

      - name: get private field
        id: private_field
        run: |
          PRIVATE=$(pnpm --filter "${{ steps.tagged_package.outputs.name }}" exec npm pkg get private)
          echo $PRIVATE
          echo "private=$PRIVATE" >> $GITHUB_OUTPUT
    outputs:
      name: ${{ steps.tagged_package.outputs.name }}
      private: ${{ steps.private_field.outputs.private }}

  publish:
    runs-on: ubuntu-latest
    needs: tagged-package
    if: needs.tagged-package.outputs.private != 'true'
    permissions:
      contents: read
      id-token: write
    steps:
      - uses: actions/checkout@v3
      - uses: pnpm/action-setup@v2
        with:
          version: 8
      - uses: actions/setup-node@v3
        with:
          node-version-file: '.nvmrc'
          cache: 'pnpm'
          registry-url: 'https://registry.npmjs.org'

      - name: install
        run: pnpm i

      - name: publish
        run: pnpm --filter "${{ needs.tagged-package.outputs.name }}" publish --access public --no-git-checks
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NODE_AUTH_TOKEN }}
          NPM_CONFIG_PROVENANCE: true
